name: app_exercicio_aula1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.4.0+2
  sqflite_common_ffi_web: ^0.4.5+3
  path: ^1.9.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/imagem.avif
