name: app_exercicio_aula1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  http: ^1.2.0
  carousel_slider: ^5.0.0   # Widget de carrossel de imagens
  image_picker: ^1.1.2      # Abre galeria/câmera/explorador de arquivos para escolher foto
  uuid: ^4.5.1              # Gera IDs únicos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/imagem.avif
